const sliderActionTypes={
    FETCH_SLIDER_MAIN_START:'FETCH_SLIDER_MAIN_START',
    FETCH_SLIDER_MAIN_SUCCESS:'FETCH_SLIDER_MAIN_SUCCESS',
    FETCH_SLIDER_MAIN_FAILURE:'FETCH_SLIDER_MAIN_FAILURE',
    FETCH_SLIDER_SECONDARY_START:'FETCH_SLIDER_SECONDARY_START',
    FETCH_SLIDER_SECONDARY_SUCCESS:'FETCH_SLIDER_SECONDARY_SUCCESS',
    FETCH_SLIDER_SECONDARY_FAILURE:'FETCH_SLIDER_SECONDARY_FAILURE'
};
export default sliderActionTypes;