const testimonialActionTypes={
    FETCH_TESTIMONIAL_START:'FETCH_TESTIMONIAL_START',
    FETCH_TESTIMONIAL_SUCCESS:'FETCH_TESTIMONIAL_SUCCESS',
    FETCH_TESTIMONIAL_FAILURE:'FETCH_TESTIMONIAL_FAILURE'
};
export default testimonialActionTypes;